# Generated by Django 2.1.10 on 2019-09-28 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateTimeField(default=django.utils.timezone.now)),
                ('inicio_contrato', models.DateTimeField()),
                ('fin_contrato', models.DateTimeField()),
                ('importe_contrato', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estrellas_contrato', models.IntegerField()),
                ('resenia_contrato', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cowork',
            fields=[
                ('id_cowork', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cowork', models.CharField(max_length=50)),
                ('direccion_cowork', models.CharField(max_length=50)),
                ('inicioTM_cowork', models.CharField(max_length=8)),
                ('finTM_cowork', models.CharField(max_length=8)),
                ('inicioTT_cowork', models.CharField(max_length=8)),
                ('finTT_cowork', models.CharField(max_length=8)),
                ('urlGoogleMaps', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_espacio', models.CharField(max_length=50)),
                ('precioMJ_espacio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioJC_espacio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ubicacion_espacio', models.CharField(max_length=100)),
                ('cowork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Cowork')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(max_length=100)),
                ('idext_pago', models.CharField(max_length=100)),
                ('importe_pago', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id_prestacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prestacion', models.CharField(max_length=50)),
                ('desc_prestacion', models.CharField(max_length=200)),
                ('icono_prestacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_puesto', models.CharField(max_length=100)),
                ('disponibilidadTM_puesto', models.BooleanField()),
                ('disponibilidadTT_puesto', models.BooleanField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni_usuario', models.IntegerField(unique=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('email_usuario', models.EmailField(max_length=70)),
                ('pass_usuario', models.CharField(max_length=30)),
                ('linkedin_usuario', models.URLField()),
                ('alta_usuario', models.DateTimeField(default=django.utils.timezone.now)),
                ('inactivo_usuario', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='espacio',
            name='prestaciones',
            field=models.ManyToManyField(to='espacios.Prestacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Puesto'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Usuario'),
        ),
    ]
