# Generated by Django 2.1.10 on 2020-02-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateTimeField(default=django.utils.timezone.now)),
                ('turno', models.CharField(blank=True, choices=[('m', 'Mañana'), ('t', 'Tarde'), ('c', 'Completo')], default='c', help_text='Turno del Contrato', max_length=1)),
                ('inicio_contrato', models.DateField()),
                ('fin_contrato', models.DateField()),
                ('importe_contrato', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estrellas_contrato', models.IntegerField(blank=True, null=True)),
                ('resenia_contrato', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cowork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_cowork', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cowork', models.CharField(max_length=50)),
                ('direccion_cowork', models.CharField(max_length=50)),
                ('inicioTM_cowork', models.CharField(max_length=8)),
                ('finTM_cowork', models.CharField(max_length=8)),
                ('inicioTT_cowork', models.CharField(max_length=8)),
                ('finTT_cowork', models.CharField(max_length=8)),
                ('lat', models.FloatField(help_text='Obtener mediante maps.google.com')),
                ('lng', models.FloatField(help_text='Obtener mediante maps.google.com')),
                ('estado', models.CharField(blank=True, choices=[('h', 'Habilitado'), ('i', 'Inhabilitado'), ('p', 'Pendiente de Aprobacion')], default='p', help_text='Estado de Cowork', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_espacio', models.CharField(max_length=50)),
                ('precioMJ_espacio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioJC_espacio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ubicacion_espacio', models.CharField(max_length=100)),
                ('es_sala', models.BooleanField()),
                ('cowork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Cowork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(max_length=50)),
                ('codpos', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(max_length=100)),
                ('idext_pago', models.CharField(blank=True, default='', max_length=100)),
                ('importe_pago', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilDeUsuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni_usuario', models.IntegerField(blank=True, default='', unique=True)),
                ('linkedin_usuario', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_prestacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prestacion', models.CharField(max_length=50)),
                ('desc_prestacion', models.CharField(max_length=200)),
                ('icono_prestacion', models.CharField(help_text='Usar caracter Unicode. Por ejemplo buscar en: https://emojis.wiki/', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Pais')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_puesto', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Provincia'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='prestaciones',
            field=models.ManyToManyField(to='espacios.Prestacion'),
        ),
        migrations.AddField(
            model_name='cowork',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Localidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.Puesto'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
