# Generated by Django 2.1.10 on 2019-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0006_auto_20191110_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='codpos',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
