# Generated by Django 2.1.10 on 2019-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0007_localidad_codpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='es_sala',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puesto',
            name='capacidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
