# Generated by Django 2.1.10 on 2020-01-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0008_auto_20191115_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='disponibilidadTM_puesto',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='disponibilidadTT_puesto',
        ),
        migrations.AddField(
            model_name='contrato',
            name='turno',
            field=models.CharField(blank=True, choices=[('m', 'Mañana'), ('t', 'Tarde'), ('c', 'Completo')], default='c', help_text='Turno del Contrato', max_length=1),
        ),
    ]
