# Generated by Django 2.1.10 on 2020-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0009_auto_20200109_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowork',
            name='urlGoogleMaps',
        ),
        migrations.AddField(
            model_name='cowork',
            name='lat',
            field=models.FloatField(default=-32.95476, help_text='Obtener mediante maps.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cowork',
            name='lng',
            field=models.FloatField(default=-60.6459824, help_text='Obtener mediante maps.google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='icono_prestacion',
            field=models.CharField(help_text='Usar caracter Unicode. Por ejemplo buscar en: https://emojis.wiki/', max_length=200),
        ),
    ]
