# Generated by Django 2.1.10 on 2020-01-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0010_auto_20200119_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fin_contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inicio_contrato',
            field=models.DateField(),
        ),
    ]
