# Generated by Django 2.1.10 on 2020-01-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0011_auto_20200125_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='contrato',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
