# Generated by Django 2.1.10 on 2020-02-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0011_auto_20200216_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='idext_pago',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
