# Generated by Django 2.1.10 on 2020-01-25 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0012_auto_20200125_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateTimeField(default=django.utils.timezone.now)),
                ('turno', models.CharField(blank=True, choices=[('m', 'Mañana'), ('t', 'Tarde'), ('c', 'Completo')], default='c', help_text='Turno del Contrato', max_length=1)),
                ('inicio_contrato', models.DateField()),
                ('fin_contrato', models.DateField()),
                ('importe_contrato', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estrellas_contrato', models.IntegerField(blank=True, null=True)),
                ('resenia_contrato', models.CharField(blank=True, max_length=250)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.Puesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(max_length=100)),
                ('idext_pago', models.CharField(max_length=100)),
                ('importe_pago', models.DecimalField(decimal_places=3, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.Contrato')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
