# Generated by Django 2.1.10 on 2020-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0012_auto_20200216_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='estado',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('i', 'Inhabilitado'), ('p', 'Pendiente de Aprobacion')], default='p', help_text='Estado de Cowork', max_length=1),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fin_contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inicio_contrato',
            field=models.DateField(),
        ),
    ]
