# Generated by Django 2.1.10 on 2020-02-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0013_contrato_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowork',
            name='estado',
            field=models.CharField(blank=True, choices=[('h', 'Habilitado'), ('i', 'Inhabilitado'), ('p', 'Pendiente de Aprobacion')], default='p', help_text='Estado de Cowork', max_length=1),
        ),
    ]
