# Generated by Django 2.1.10 on 2020-02-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0016_auto_20200207_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_coadmin',
            field=models.BooleanField(default=False),
        ),
    ]
