# Generated by Django 2.1.10 on 2020-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0017_auto_20200209_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_usuario',
            field=models.URLField(blank=True),
        ),
    ]
