# Generated by Django 2.1.10 on 2020-02-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0018_auto_20200209_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_coadmin',
        ),
    ]
