# Generated by Django 2.1.10 on 2019-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
