# Generated by Django 2.1.10 on 2019-10-04 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('espacios', '0002_auto_20190928_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('dni_usuario', models.IntegerField(unique=True)),
                ('linkedin_usuario', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='espacios.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
